### ISSUE TITLE
can't use tockloader on nRF51dk

### ISSUE THREAD

**Issue by niklasad1** [helena-project/tockloader#15]
Hi,
I can't manage to get tockloader to flash userapps in TockOS

Version info:
```
➜  ~ uname -a                  
Linux desktop 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
➜  ~ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
➜  tock git:(master) ✗ tockloader --version                                        
0.7.1
```
When I flash the board everything looks fine:
```
➜  blink git:(master) ✗ tockloader install --jtag --board nrf51dk --arch cortex-m0
No TABs passed to tockloader. Searching for TABs in subdirectories.
Using: ['./build/blink.tab']
Waiting one second before continuing...
Installing apps on the board...
Finished in 1.446 seconds
```
But the LEDs don't blink!!

Listen works:
```
➜  blink git:(master) ✗ tockloader listen
No device name specified. Using default "tock"
No serial port with device name "tock" found
Found 3 serial port(s).

[0]	/dev/ttyS1 - n/a
[1]	/dev/ttyS0 - ttyS0
[2]	/dev/ttyACM0 - J-Link - CDC

Which option? [0] 2

Listening for serial output.
TOCK_DEBUG(0): src/main.rs:284: Initialization complete. Entering main loop
```
List don't work
```
➜  blink git:(master) ✗ tockloader list  
No device name specified. Using default "tock"
No serial port with device name "tock" found
Found 3 serial port(s).

[0]	/dev/ttyS1 - n/a
[1]	/dev/ttyS0 - ttyS0
[2]	/dev/ttyACM0 - J-Link - CDC

Which option? [0] 2

Error connecting to bootloader. No "pong" received.
Things that could be wrong:
  - The bootloader is not flashed on the chip
  - The DTR/RTS lines are not working
  - The serial port being used is incorrect
  - The bootloader API has changed
  - There is a bug in this script
Could not attach to the bootloader
```

What am I doing wrong?

**Comment by brghena** [comment]
Try list again as `tockloader list --jtag`. That response means that there is no bootloader responding over serial. (And selecting JTAG there meant that tockloader tried to send serial commands to the JTAG module).

If there isn't a serial bootloader, tockloader requires the `--jtag` flag for every command except listen.

**Comment by niklasad1** [comment]
It did work at least with some more arguments when using ```list```, see below
```
➜  blink git:(nRF52/BLE) ✗ tockloader install --jtag --board nrf51dk --arch cortex-m0
No TABs passed to tockloader. Searching for TABs in subdirectories.
Using: ['./build/blink.tab']
Waiting one second before continuing...
Installing apps on the board...
Finished in 1.437 seconds

➜  blink git:(nRF52/BLE) ✗ tockloader list --jtag --board nrf51dk --arch cortex-m0   
No found apps.
Finished in 0.350 seconds
```
Also tried ```info```
```
➜  blink git:(nRF52/BLE) ✗ tockloader info --jtag --arch cortex-mo --board nrf51dk   
tockloader version: 0.7.1
Showing all properties of the board...
Apps:
No found apps.
Traceback (most recent call last):
  File "/usr/bin/tockloader", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/tockloader/main.py", line 479, in main
    args.func(args)
  File "/usr/lib/python3.6/site-packages/tockloader/main.py", line 231, in command_info
    tock_loader.info(args.app_address)
  File "/usr/lib/python3.6/site-packages/tockloader/tockloader.py", line 388, in info
    if self._bootloader_is_present():
  File "/usr/lib/python3.6/site-packages/tockloader/tockloader.py", line 481, in _bootloader_is_present
    flag_str = flag.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 3: invalid start byte
```
What does it mean?

**Comment by bradjc** [comment]
Try the commands again with `--jtag-device <same device as you pass to JLinkExe>`.

As for the errors, my guess is that the install command isn't actually working. The error handing when calling into JLinkExe isn't the best. It could also be on the read side, but hopefully specifying the device will help.

**Comment by niklasad1** [comment]
1. Only kernel flashed on the device
```
➜  blink git:(master) ✗ tockloader list --jtag --board nrf51dk --arch cortex-m0 --jtag-device NRF51822_XXAA
No found apps.
Finished in 0.514 seconds
```
2. Flash the userapp using tockloader with --jtag--device option
```
➜  blink git:(master) ✗ tockloader install --jtag --board nrf51dk --arch cortex-m0 --jtag-device NRF51822_XXAA
No TABs passed to tockloader. Searching for TABs in subdirectories.
Using: ['./build/blink.tab']
Waiting one second before continuing...
Installing apps on the board...
Finished in 1.706 seconds
```

3. Check if the userapp was uploaded to the board
```
➜  blink git:(master) ✗ tockloader list --jtag --board nrf51dk --arch cortex-m0 --jtag-device NRF51822_XXAA
[App 0]
  Name:                  blink
  Enabled:               True
  Sticky:                False
  Total Size in Flash:   2048 bytes


Finished in 1.010 seconds
```

4. No LEDs is blinking 😭

**Comment by Tiwalun** [comment]
I had a similar problem with the nrf52dk, and managed to get this to work with the following command:

```
➜  blink git:(master) ✗ tockloader install --jtag --board nrf52dk --arch cortex-m4 --app-address 0x20000 --jtag-device nrf52
No TABs passed to tockloader. Searching for TABs in subdirectories.
Using: ['./build/blink.tab']
Waiting one second before continuing...
Installing apps on the board...
Finished in 1.861 seconds
```

The problems seems to be that by default, tockloader tries to install the app at address 0x3000 which doesn't work. When installing with `make TOCK_BOARD=nrf52dk flash`, it uses 0x20000 as the installation address, and using that with tockloader works as well.

**Comment by niklasad1** [comment]
@Tiwalun Thanks, it works both on nrf52dk and nrf51dk
